server:
  port: 8091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webstore



#
#spring:
#  application:
#    name: product-service
#  cloud:
#    config:
#      url: http://localhost:9999

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka,http://localhost:8082/eureka

